name: Busca Diária de Licitações

on:
  workflow_dispatch: # Permite iniciar manualmente pela interface do GitHub
  schedule:
    # Roda todos os dias às 15:00 UTC (12:00 no horário de Brasília)
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar arquivo de credenciais do Google
        # Esta etapa pega o conteúdo do "cofre" e cria o arquivo credentials.json no servidor
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      - name: Rodar Robô de Coleta (app.py)
        run: python app.py

      - name: Rodar Robô de Processamento (processador.py)
        run: python processador.py
